### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Effects/GeometryFX#1]
I would like to point out that an identifier like "[`__AMD_GEOMETRYFX_FILTERING_H__`](https://github.com/GPUOpen-Effects/GeometryFX/blob/958ec9cd7ebeef2365e9efe6ad664985c32339fd/amd_geometryfx/inc/AMD_GeometryFX_Filtering.h#L23)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jstewart-amd** [comment]
While double underscore is technically illegal, its use in libraries in commonplace. Still, we will consider changing our include guard naming convention. Thanks for the feedback.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?

Will it be better to keep this issue open until all affected components will be fixed?

**Comment by jstewart-amd** [comment]
Reopening this issue. A commit will be pushed soon that cleans up include guard naming.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/GPUOpen-Effects/GeometryFX/commit/7db682d6689205e434a7d78b25c1f3802c36d760).
