### ISSUE TITLE
Newlines at end of source files

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Effects/GeometryFX#3]
[How do you think about](http://stackoverflow.com/questions/72271/no-newline-at-end-of-file-compiler-warning) to [add newlines at the end of a few source files](https://github.com/GPUOpen-Effects/GeometryFX/commit/7db682d6689205e434a7d78b25c1f3802c36d760#diff-0c0f6bb3653ab9a7afc5b4e8268307baL50)?

**Comment by jstewart-amd** [comment]
A cleanup pass was done to bring the code into compliance with our style guidelines. This included adding newlines at the end of source files.

See cacb1aaca3c3fea464f852177abeb82e1bbe41fb for more information.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/GPUOpen-Effects/GeometryFX/commit/cacb1aaca3c3fea464f852177abeb82e1bbe41fb#diff-0c0f6bb3653ab9a7afc5b4e8268307baL50).
