### ISSUE TITLE
Can this library handle Alpha Testing?

### ISSUE THREAD

**Issue by moonshineTheleocat** [GPUOpen-Effects/GeometryFX#5]
I thought about using this library, but I'm not entirely sure how it culls it's geometry. So I was wandering if it can handle Alpha testing well enough for scenes with large amounts of cutouts.

**Comment by Anteru** [comment]
No, it assumes for now that the geometry is 100% opaque. It works on triangles, and doesn't sample textures. The only filter which could benefit is the small triangle filter, but given that cutout triangles are generally large, I don't think it'll be worth the trouble. The most effective filter (backface culling) won't have any effect if your transparent objects are double-sided (which they generally are).
