### ISSUE TITLE
Poor performance in the sample

### ISSUE THREAD

**Issue by jesta88** [GPUOpen-Effects/GeometryFX#6]
Enabling filtering nearly doubles frame time on the sample. I'm not sure whether this is normal or not considering the mesh used, but maybe it would be a good idea to have a "stress test" sample to showcase the performance gain.

**Comment by Anteru** [comment]
I've just tried on a RX 480, 17.12.2 driver. With filter: 0.21 ms, without: 0.26 ms (that is, with filtering it's 20% faster). On a Vega RX 64, it's 0.15 ms with filtering, and 0.23 ms without filtering (filtering is nearly 30% faster). On which GPU do you see a doubling in execution time?

**Comment by jesta88** [comment]
I'm on a GTX 960, driver 388.59

**Comment by dariomanesku** [comment]
I observed the same behaviour on GTX 1060. I tried different meshes, different view angles, different options.. enabling filter always made it slower.

**Comment by Anteru** [comment]
GeometryFX is designed for AMD hardware – it uses async compute to overlap the filtering with the rendering, and implements filtering techniques not directly available on the hardware. On other vendors, performance may vary significantly.
